version: '3.8'

services:
  mpms:
    build: .
    hostname: mpms
    container_name: mpms
    ports:
      - "8080:8080"
    networks:
      - mpms-demo

  mail-hog:
    image: mailhog/mailhog
    hostname: mail-hog
    container_name: mail-hog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mpms-demo


networks:
  mpms-demo: