spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda:
  bpm:
    admin-user:
      id: eurodyn
      password: eurodyn

    deployment-resource-pattern:
      - classpath*:**/*.bpmn
      - classpath*:**/*.form
    authorization:
      enabled: true

logging:
  level:
    org:
      camunda.bpm.client.spring: DEBUG